#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login_check
  methods:  [POST]
owner:
  type: rest
  resource: App\Controller\OwnerController
Accommodation:
  type: rest
  resource: App\Controller\AccommodationController
CarRent:
  type: rest
  resource: App\Controller\CarRentController
Taxi:
  type: rest
  resource: App\Controller\TaxiController
User:
  type: rest
  resource: App\Controller\UserController

